### PR TITLE
feat: add mongo_api:ping/2

### PR DESCRIPTION
**Pull request by terry-xiaoyu**
Add `mongo_api:ping/2` for health check purposes. It will be called by the `emqx_backend_mongo_actions:on_get_resource_status` to test if the connection between emqx and mongodb works well.

Before this change, we have to use `mongo_api:find_one(Conn, <<"foo">>, {}, #{}, 0, infinity)` to test the connectivity, where <<"foo">> is a dummy collection may or may not be present in the mongodb.

### CODE REVIEW

**Comment by kjellwinblad** [comment]
@terry-xiaoyu can you explain what the purpose of the ping command is. Could the user not get the same functionality from calling the `command` functions?

**Comment by kjellwinblad** [comment]
I think it is better to add a `command/2` function to the `mongo_api` module that is similar to the `command/2` function in the `mc_worker_api` module. Then we will have a much more general function that can be used to execute [many Mongo DB commands](https://www.mongodb.com/docs/manual/reference/command/) and not only ping.

@terry-xiaoyu what do you think?

**Comment by terry-xiaoyu** [comment]
> I think it is better to add a `command/2` function to the `mongo_api` module that is similar to the `command/2` function in the `mc_worker_api` module. Then we will have a much more general function that can be used to execute [many Mongo DB commands](https://www.mongodb.com/docs/manual/reference/command/) and not only ping.
> 
> @terry-xiaoyu what do you think?

OK, I will add a command API too.

**Comment by terry-xiaoyu** [comment]
Updated: 

Added the `mongo_api:command/3`, and removed the ping API.

**Review by kjellwinblad — APPROVED** [review]
Looks good to me

**Pull request merged**
